services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=pawlie
      - DATABASE_NAME=pawlie
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pawlie-network

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - pawlie-network

  adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    networks:
      - pawlie-network

volumes:
  redis_data:

networks:
  pawlie-network:
    driver: bridge